import { z } from "zod";
import { DEFAULT_LIMIT, DEFAULT_MAX_PAGES, MAX_PAGES, MAX_STRAVA_LIMIT } from "../constants.js";
import { AGENT_CLIENTS } from "../services/agent-manifest.js";

export const ResponseFormatSchema = z.enum(["markdown", "json"]).default("markdown");
export const AgentClientSchema = z.enum(AGENT_CLIENTS).default("generic");
export const PrivacyModeValueSchema = z.enum(["summary", "structured", "raw"]);
export const PrivacyModeSchema = PrivacyModeValueSchema.optional()
  .describe("Optional per-call privacy override. Defaults to STRAVA_PRIVACY_MODE or structured. raw returns upstream Strava JSON. summary removes GPS/map details.");

export const DateTimeSchema = z.string()
  .datetime({ offset: true })
  .optional()
  .describe("ISO 8601 date-time with timezone, e.g. 2026-05-01T00:00:00Z");

export const CollectionInputSchema = z.object({
  after: DateTimeSchema.describe("Only return activities after this time. Converted to Strava epoch seconds."),
  before: DateTimeSchema.describe("Only return activities before this time. Converted to Strava epoch seconds."),
  page: z.number().int().min(1).default(1).describe("Strava page number."),
  limit: z.number().int().min(1).max(MAX_STRAVA_LIMIT).default(DEFAULT_LIMIT)
    .describe("Strava per_page value. Strava allows up to 200."),
  all_pages: z.boolean().default(false).describe("Fetch multiple pages up to max_pages."),
  max_pages: z.number().int().min(1).max(MAX_PAGES).default(DEFAULT_MAX_PAGES)
    .describe("Maximum pages to fetch when all_pages is true."),
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const IdInputSchema = z.object({
  id: z.union([z.string().min(1), z.number().int().positive()]).describe("Strava resource id."),
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const ActivityStreamsInputSchema = z.object({
  id: z.union([z.string().min(1), z.number().int().positive()]).describe("Strava activity id."),
  keys: z.array(z.enum(["time", "distance", "latlng", "altitude", "velocity_smooth", "heartrate", "cadence", "watts", "temp", "moving", "grade_smooth"])).default(["time", "distance", "heartrate", "cadence", "watts", "altitude"])
    .describe("Stream keys to request. latlng is withheld unless privacy_mode=raw or include_gps=true."),
  include_gps: z.boolean().default(false).describe("Allow latlng stream in structured output. Raw mode always returns requested upstream payload."),
  resolution: z.enum(["low", "medium", "high"]).optional().describe("Optional Strava stream resolution."),
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const SimpleReadInputSchema = z.object({
  privacy_mode: PrivacyModeSchema,
  response_format: ResponseFormatSchema
}).strict();

export const ResponseOnlyInputSchema = z.object({
  response_format: ResponseFormatSchema
}).strict();

export const AgentManifestInputSchema = z.object({
  client: AgentClientSchema,
  response_format: ResponseFormatSchema
}).strict();

export const ConnectionStatusInputSchema = z.object({
  client: AgentClientSchema.optional(),
  response_format: ResponseFormatSchema
}).strict();

export const AuthUrlInputSchema = z.object({
  state: z.string().max(500).optional().describe("Optional OAuth state value generated by the caller."),
  scopes: z.array(z.string()).optional().describe("Optional scope override. Defaults to read-only Strava scopes used by this server."),
  response_format: ResponseFormatSchema
}).strict();

export const ExchangeCodeInputSchema = z.object({
  code: z.string().min(1).describe("OAuth authorization code, or a full redirect URL containing ?code=..."),
  response_format: ResponseFormatSchema
}).strict();

export const DailySummaryInputSchema = z.object({
  days: z.number().int().min(1).max(30).default(7).describe("Lookback window for recent training context."),
  timezone: z.string().min(1).max(80).default("UTC").describe("IANA timezone used only for display, e.g. America/New_York."),
  response_format: ResponseFormatSchema
}).strict();

export const TrainingContextInputSchema = z.object({
  days: z.number().int().min(1).max(30).default(7).describe("Lookback window for normalized Strava training context."),
  timezone: z.string().min(1).max(80).default("UTC").describe("IANA timezone used only for display, e.g. America/New_York."),
  soreness: z.array(z.string().min(1).max(80)).default([]),
  injury_flags: z.array(z.string().min(1).max(120)).default([]),
  notes: z.string().max(500).optional(),
  response_format: ResponseFormatSchema
}).strict();

export const WeeklySummaryInputSchema = z.object({
  days: z.number().int().min(7).max(60).default(7).describe("Recent analysis window in days."),
  compare_days: z.number().int().min(0).max(60).default(7).describe("Prior comparison window in days. Use 0 to disable comparison."),
  timezone: z.string().min(1).max(80).default("UTC").describe("IANA timezone used only for display, e.g. America/New_York."),
  response_format: ResponseFormatSchema
}).strict();

export const AuthUrlOutputSchema = z.object({
  auth_url: z.string(),
  redirect_uri: z.string(),
  scopes: z.array(z.string()),
  next_step: z.string()
}).strict();

export const ExchangeCodeOutputSchema = z.object({
  ok: z.boolean(),
  token_path: z.string(),
  scope: z.string().optional(),
  expires_at: z.number().optional(),
  note: z.string()
}).strict();

export const EndpointDataOutputSchema = z.object({
  endpoint: z.string(),
  privacy_mode: PrivacyModeValueSchema,
  data: z.unknown()
}).strict();

export const CollectionOutputSchema = z.object({
  endpoint: z.string(),
  privacy_mode: PrivacyModeValueSchema,
  count: z.number().int().nonnegative(),
  records: z.array(z.unknown()),
  next_page: z.number().int().positive().optional(),
  has_more: z.boolean(),
  pages_fetched: z.number().int().nonnegative()
}).strict();

export const CacheStatusOutputSchema = z.object({
  enabled: z.boolean(),
  path: z.string(),
  entries: z.number().int().nonnegative(),
  newest_cached_at: z.string().optional()
}).strict();

export const RevokeAccessOutputSchema = z.object({
  ok: z.boolean(),
  token_path: z.string(),
  local_tokens_cleared: z.boolean(),
  note: z.string()
}).strict();

export const PrivacyAuditOutputSchema = z.object({
  project: z.string(),
  unofficial: z.boolean(),
  config_source: z.enum(["env", "local_config", "mixed", "missing"]),
  local_config_path: z.string(),
  local_config_exists: z.boolean(),
  local_config_secure_permissions: z.boolean().optional(),
  privacy_mode_default: PrivacyModeValueSchema,
  raw_payloads_opt_in: z.boolean(),
  gps_redaction_default: z.boolean(),
  cache_enabled: z.boolean(),
  cache_path: z.string(),
  token_path: z.string(),
  stdout_safe: z.boolean(),
  secret_env_vars: z.array(z.string()),
  required_env_present: z.record(z.string(), z.boolean()),
  redacted_key_patterns: z.array(z.string()),
  notes: z.array(z.string())
}).strict();

export const CapabilitiesOutputSchema = z.object({
  project: z.string(),
  mcp_name: z.string(),
  creator: z.object({ name: z.string(), github: z.string() }).strict(),
  unofficial: z.boolean(),
  api_boundary: z.object({ source: z.string(), raw_definition: z.string(), does_not_include: z.array(z.string()) }).strict(),
  auth_model: z.object({ type: z.string(), token_storage: z.string(), recommended_redirect_uri: z.string(), default_scopes: z.array(z.string()) }).strict(),
  privacy_modes: z.array(z.object({ mode: PrivacyModeValueSchema, use_when: z.string() }).strict()),
  supported_data: z.array(z.object({ name: z.string(), examples: z.array(z.string()), tools: z.array(z.string()) }).strict()),
  recommended_agent_flow: z.array(z.string()),
  client_aliases: z.object({
    hermes: z.object({
      tool_prefix: z.string(),
      direct_tools: z.array(z.string()),
      reload_command: z.string(),
      gateway_restart_required_for_data_access: z.boolean()
    }).strict()
  }).strict(),
  contribution_paths: z.array(z.string()),
  links: z.record(z.string(), z.string())
}).passthrough();

export const AgentManifestOutputSchema = z.object({
  project: z.string(),
  mcp_name: z.string(),
  client: AgentClientSchema,
  unofficial: z.boolean(),
  package: z.object({
    name: z.string(),
    version: z.string(),
    install_command: z.string(),
    pinned_install_command: z.string(),
    binary: z.string()
  }).strict(),
  oauth: z.object({
    provider: z.string(),
    redirect_uri: z.string(),
    scopes: z.array(z.string()),
    token_storage: z.string(),
    secret_storage: z.string()
  }).strict(),
  recommended_first_calls: z.array(z.string()),
  standard_tools: z.array(z.string()),
  resources: z.array(z.string()),
  hermes: z.object({
    config_path: z.string(),
    skill_path: z.string(),
    tool_name_prefix: z.string(),
    common_tool_names: z.array(z.string()),
    recommended_config: z.string(),
    use_direct_tools: z.boolean(),
    avoid_terminal_workarounds: z.boolean(),
    no_gateway_restart_for_data_access: z.boolean(),
    reload_after_config_change: z.string(),
    doctor_command: z.string()
  }).strict(),
  agent_rules: z.array(z.string()),
  troubleshooting: z.array(z.object({ symptom: z.string(), action: z.string() }).strict()),
  links: z.record(z.string(), z.string())
}).strict();

export const ConnectionStatusOutputSchema = z.object({
  ok: z.boolean(),
  ready_for_strava_api: z.boolean(),
  effective_status: z.enum(["missing_config", "missing_token", "expired", "refreshable", "ready"]),
  client: AgentClientSchema.optional(),
  node: z.object({ version: z.string(), supported: z.boolean() }).strict(),
  privacy_mode: PrivacyModeValueSchema,
  required_env: z.record(z.string(), z.boolean()),
  missing_env: z.array(z.string()),
  redirect_uri: z.string().optional(),
  automatic_auth_supported: z.boolean(),
  config: z.object({ source: z.enum(["env", "local_config", "mixed", "missing"]), path: z.string(), exists: z.boolean(), secure_permissions: z.boolean().optional(), error: z.string().optional() }).strict(),
  token: z.object({ path: z.string(), exists: z.boolean(), readable: z.boolean(), permissions: z.string().optional(), secure_permissions: z.boolean().optional(), expires_at: z.number().optional(), expired: z.boolean().optional(), has_refresh_token: z.boolean().optional(), scope: z.string().optional(), error: z.string().optional() }).strict(),
  oauth: z.object({
    recommended_scopes: z.array(z.string()),
    granted_scopes: z.array(z.string()),
    missing_recommended_scopes: z.array(z.string()),
    scope_status: z.enum(["ok", "missing_recommended", "unknown", "missing_token"]),
    activity_tools_ready: z.boolean(),
    profile_tools_ready: z.boolean()
  }).strict(),
  cache: z.object({ enabled: z.boolean(), path: z.string() }).strict(),
  client_checks: z.object({
    hermes: z.object({
      config_path: z.string(),
      config_exists: z.boolean(),
      strava_server_configured: z.boolean(),
      package_pinned: z.boolean(),
      mcp_reload_confirmation_disabled: z.boolean().optional(),
      skill_path: z.string(),
      skill_installed: z.boolean(),
      direct_tool_prefix: z.string(),
      expected_direct_tools: z.array(z.string()),
      recommendations: z.array(z.string()),
      error: z.string().optional()
    }).strict().optional()
  }).strict().optional(),
  next_steps: z.array(z.string())
}).strict();


export const DataInventoryOutputSchema = z.object({
  kind: z.literal("data_inventory"),
  source: z.string(),
  mcp_name: z.string(),
  generated_at: z.string(),
  unofficial: z.boolean(),
  data_access_model: z.string(),
  auth: z.unknown().optional(),
  scopes: z.array(z.string()),
  api_boundary: z.unknown().optional(),
  privacy_modes: z.array(z.unknown()),
  categories: z.array(z.object({
    name: z.string(),
    examples: z.array(z.string()),
    tools: z.array(z.string())
  }).strict()),
  totals: z.object({
    categories: z.number().int().nonnegative(),
    listed_tools: z.number().int().nonnegative(),
    scopes: z.number().int().nonnegative()
  }).strict(),
  first_tools: z.array(z.string()),
  recommended_agent_flow: z.array(z.string()),
  links: z.record(z.string(), z.string()),
  notes: z.array(z.string())
}).strict();

export const SummaryOutputSchema = z.object({
  kind: z.enum(["daily_summary", "weekly_summary"]),
  generated_at: z.string()
}).passthrough();

export const TrainingContextOutputSchema = z.object({
  source: z.literal("strava"),
  context_contract_version: z.literal("delx-wellness-context/v1"),
  context_type: z.literal("training_context"),
  generated_at: z.string(),
  recent_training_load: z.enum(["low", "normal", "high", "unknown"]),
  last_activity_type: z.unknown().optional(),
  weekly_minutes: z.number().nonnegative().optional(),
  relative_effort: z.number().nonnegative().optional(),
  privacy: z.object({
    gps: z.literal("withheld_from_context"),
    route_details: z.literal("not_included"),
  }).strict(),
  recommended_handoff: z.object({ tool: z.string(), reason: z.string() }).strict(),
  soreness_hint: z.number().nonnegative().optional(),
  soreness: z.array(z.string()),
  injury_flags: z.array(z.string()),
  notes: z.array(z.string()).optional(),
  data_quality: z.unknown().optional(),
  fallback_hint: z.string().optional(),
  telegram_summary: z.string().optional()
}).strict();

export type CollectionInput = z.infer<typeof CollectionInputSchema>;
export type IdInput = z.infer<typeof IdInputSchema>;
export type ActivityStreamsInput = z.infer<typeof ActivityStreamsInputSchema>;
export type SimpleReadInput = z.infer<typeof SimpleReadInputSchema>;
export type ResponseOnlyInput = z.infer<typeof ResponseOnlyInputSchema>;
export type AgentManifestInput = z.infer<typeof AgentManifestInputSchema>;
export type AuthUrlInput = z.infer<typeof AuthUrlInputSchema>;
export type ExchangeCodeInput = z.infer<typeof ExchangeCodeInputSchema>;
export type DailySummaryInput = z.infer<typeof DailySummaryInputSchema>;
export type TrainingContextInput = z.infer<typeof TrainingContextInputSchema>;
export type WeeklySummaryInput = z.infer<typeof WeeklySummaryInputSchema>;
